# Generated by Django 6.1.1 on 2026-10-04 11:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DutyRoster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('next_return_date', models.DateField(blank=True, null=True, verbose_name='تاريخ العودة القادم')),
                ('notes', models.CharField(blank=True, max_length=500, verbose_name='ملاحظات')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='duty_rosters', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'جدول دوام',
                'verbose_name_plural': 'جداول الدوام',
                'db_table': 'duty_roster',
            },
        ),
    ]
