# Generated by Django 6.1.1 on 2026-10-04 11:30

import accounts.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('org', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('military_id', models.CharField(max_length=20, unique=True, verbose_name='الرقم العسكري')),
                ('full_name', models.CharField(max_length=150, verbose_name='الاسم الكامل')),
                ('rank', models.CharField(blank=True, max_length=50, verbose_name='الرتبة')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='الجوال')),
                ('email', models.EmailField(blank=True, max_length=150, verbose_name='البريد الإلكتروني')),
                ('role', models.CharField(choices=[('SOLDIER', 'عسكري'), ('OFFICER', 'ضابط / قائد'), ('FINANCE', 'الشؤون المالية'), ('ADMIN', 'مدير النظام')], default='SOLDIER', max_length=30, verbose_name='الدور')),
                ('status', models.CharField(choices=[('ACTIVE', 'على رأس العمل'), ('SUSPENDED', 'موقوف'), ('TRANSFERRED', 'منقول')], default='ACTIVE', max_length=20, verbose_name='الحالة')),
                ('failed_attempts', models.PositiveIntegerField(default=0, verbose_name='محاولات الدخول الفاشلة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='members', to='org.unit', verbose_name='الوحدة')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'مستخدم',
                'verbose_name_plural': 'المستخدمون',
                'db_table': 'users',
            },
            managers=[
                ('objects', accounts.models.UserManager()),
            ],
        ),
    ]
