# Generated by Django 6.1.1 on 2026-10-04 11:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=50, verbose_name='الإجراء')),
                ('object_type', models.CharField(blank=True, max_length=50, verbose_name='نوع الكائن')),
                ('object_id', models.CharField(blank=True, max_length=50, verbose_name='معرف الكائن')),
                ('details', models.JSONField(blank=True, default=dict, verbose_name='تفاصيل')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='الوقت')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'سجل تدقيق',
                'verbose_name_plural': 'سجل التدقيق',
                'db_table': 'audit_logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
