# Generated by Django 6.1.1 on 2026-10-04 11:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('org', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='الاسم')),
                ('icon', models.CharField(blank=True, max_length=50, verbose_name='الأيقونة')),
            ],
            options={
                'verbose_name': 'تصنيف طلب',
                'verbose_name_plural': 'تصنيفات الطلبات',
                'db_table': 'request_categories',
            },
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_number', models.CharField(max_length=30, unique=True, verbose_name='رقم الطلب')),
                ('reason', models.TextField(blank=True, max_length=1000, verbose_name='السبب / التفاصيل')),
                ('date_from', models.DateField(blank=True, null=True, verbose_name='من تاريخ')),
                ('date_to', models.DateField(blank=True, null=True, verbose_name='إلى تاريخ')),
                ('priority', models.CharField(choices=[('NORMAL', 'عادي'), ('URGENT', 'عاجل'), ('EMERGENCY', 'طارئ')], default='NORMAL', max_length=20, verbose_name='الأولوية')),
                ('status', models.CharField(choices=[('PENDING', 'قيد المراجعة'), ('PENDING_EDIT', 'معاد للتعديل'), ('APPROVED', 'معتمد'), ('REJECTED', 'مرفوض'), ('COMPLETED', 'مكتمل'), ('CANCELLED', 'ملغى')], default='PENDING', max_length=20, verbose_name='الحالة')),
                ('manning_warning', models.BooleanField(default=False, verbose_name='تنبيه الحد الأدنى')),
                ('current_step', models.PositiveSmallIntegerField(default=1, verbose_name='الخطوة الحالية')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requests', to=settings.AUTH_USER_MODEL, verbose_name='مقدم الطلب')),
            ],
            options={
                'verbose_name': 'طلب',
                'verbose_name_plural': 'الطلبات',
                'db_table': 'requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ManningCheckLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_from', models.DateField(verbose_name='من تاريخ')),
                ('date_to', models.DateField(verbose_name='إلى تاريخ')),
                ('result', models.CharField(choices=[('OK', 'ضمن الحد'), ('BELOW_MINIMUM', 'أقل من الحد الأدنى')], max_length=20, verbose_name='النتيجة')),
                ('affected_dates', models.JSONField(blank=True, default=list, verbose_name='الأيام المتأثرة')),
                ('checked_at', models.DateTimeField(auto_now_add=True, verbose_name='وقت الفحص')),
                ('checked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='manning_checks', to=settings.AUTH_USER_MODEL, verbose_name='بواسطة')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='manning_checks', to='org.site', verbose_name='الموقع')),
                ('request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='manning_checks', to='requests_app.request', verbose_name='الطلب')),
            ],
            options={
                'verbose_name': 'فحص الحد الأدنى',
                'verbose_name_plural': 'سجل فحص الحد الأدنى',
                'db_table': 'manning_check_logs',
                'ordering': ['-checked_at'],
            },
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='attachments/%Y/%m/', verbose_name='الملف')),
                ('file_name', models.CharField(max_length=255, verbose_name='اسم الملف')),
                ('file_size', models.PositiveIntegerField(blank=True, null=True, verbose_name='الحجم (بايت)')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الرفع')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='requests_app.request', verbose_name='الطلب')),
            ],
            options={
                'verbose_name': 'مرفق',
                'verbose_name_plural': 'المرفقات',
                'db_table': 'attachments',
            },
        ),
        migrations.CreateModel(
            name='ApprovalAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision', models.CharField(choices=[('APPROVE', 'اعتماد'), ('REJECT', 'رفض'), ('RETURN', 'إعادة للتعديل'), ('FORWARD', 'إحالة')], max_length=20, verbose_name='القرار')),
                ('reason', models.TextField(blank=True, max_length=1000, verbose_name='السبب')),
                ('manning_acknowledged', models.BooleanField(default=False, verbose_name='أقر بتنبيه الحد الأدنى')),
                ('action_date', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإجراء')),
                ('approver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='approval_actions', to=settings.AUTH_USER_MODEL, verbose_name='المعتمد')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='actions', to='requests_app.request', verbose_name='الطلب')),
            ],
            options={
                'verbose_name': 'إجراء اعتماد',
                'verbose_name_plural': 'سجل الاعتمادات',
                'db_table': 'approval_actions',
                'ordering': ['action_date'],
            },
        ),
        migrations.CreateModel(
            name='RequestType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='الاسم')),
                ('requires_dates', models.BooleanField(default=False, verbose_name='يتطلب تواريخ')),
                ('requires_attachment', models.BooleanField(default=False, verbose_name='يتطلب مرفق')),
                ('is_leave_type', models.BooleanField(default=False, verbose_name='نوع إجازة')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='types', to='requests_app.requestcategory', verbose_name='التصنيف')),
            ],
            options={
                'verbose_name': 'نوع طلب',
                'verbose_name_plural': 'أنواع الطلبات',
                'db_table': 'request_types',
            },
        ),
        migrations.AddField(
            model_name='request',
            name='request_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requests', to='requests_app.requesttype', verbose_name='نوع الطلب'),
        ),
        migrations.CreateModel(
            name='ApprovalChainStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_order', models.PositiveSmallIntegerField(verbose_name='ترتيب الخطوة')),
                ('approver_role', models.CharField(choices=[('OFFICER', 'ضابط / قائد'), ('FINANCE', 'الشؤون المالية'), ('ADMIN', 'مدير النظام')], max_length=30, verbose_name='دور المعتمد')),
                ('request_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chain_steps', to='requests_app.requesttype', verbose_name='نوع الطلب')),
            ],
            options={
                'verbose_name': 'خطوة اعتماد',
                'verbose_name_plural': 'مسارات الاعتماد',
                'db_table': 'approval_chain_steps',
                'ordering': ['request_type', 'step_order'],
            },
        ),
        migrations.AddConstraint(
            model_name='request',
            constraint=models.CheckConstraint(condition=models.Q(('date_from__isnull', True), ('date_to__isnull', True), ('date_to__gte', models.F('date_from')), _connector='OR'), name='ck_requests_dates'),
        ),
        migrations.AddConstraint(
            model_name='approvalchainstep',
            constraint=models.UniqueConstraint(fields=('request_type', 'step_order'), name='uq_chain_step_order'),
        ),
    ]
