# Generated by Django 6.0.5 on 2026-10-04 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='priority',
            field=models.CharField(choices=[('NORMAL', 'عاديه'), ('URGENT', 'عاجله'), ('EMERGENCY', 'طارئه')], default='NORMAL', max_length=20, verbose_name='الأولوية'),
        ),
    ]
